@sut = actuator/translation-count

### Reset Translation Counter
DELETE {{host}}/{{sut}}

?? status == 204

### Zero Translation Counter
GET {{host}}/{{sut}}

?? status == 200
?? body count == 0

### Translate first sentence
POST {{host}}/pig-latin
Content-Type: application/json

{
    "sentence": "Hello, World!"
}

?? status == 200
?? header content-type == application/json
?? body sentence == ellohay, orldway!

### Check Translation Counter
GET {{host}}/{{sut}}

?? status == 200
?? body count == 1

### Translate second sentence
POST {{host}}/pig-latin
Content-Type: application/json

{
    "sentence": "The quick brown fox jumps over the lazy dog."
}

?? status == 200
?? header content-type == application/json
?? body sentence == ethay ickquay ownbray oxfay umpsjay overay ethay azylay ogday.

### Second Counter Check
GET {{host}}/{{sut}}

?? status == 200
?? body count == 2

### Set Translation Counter
POST {{host}}/{{sut}}
Content-Type: application/json

{"count": 9}

?? status == 200
?? body count == 9

### Check Changed Counter
GET {{host}}/{{sut}}

?? status == 200
?? body count == 9
