### Swagger UI

GET {{host}}/swagger-ui/index.html

> {% import './scripts/validate-200-response';

    client.test("Response body contains 'swagger-ui'", function () {
        client.assert(response.body.match(/swagger-ui/), "Response doesn't contains 'swagger-ui'");
    });
%}
