### Bad request (payload is null)

POST {{host}}/pig-latin
Content-Type: application/json
Accept: application/json

null

> {%
    import './scripts/validate-200-response';
    import './scripts/validate-content-json';

    client.test("Sentence option exists", function () {
        client.assert(response.body.hasOwnProperty("sentence"), "Cannot find 'sentence' option in response");
    });
%}
