### Bad request (payload is null)

POST {{host}}/pig-latin
Content-Type: application/json
Accept: application/json

null

> {%
    import './scripts/validate-content-json';
    client.test("Request returns status 400", function () {
        client.assert(response.status === 400, `Expected '400' but received '${response.status}'`);
    });
    client.test("Error option exists", function () {
        client.assert(response.body.hasOwnProperty("error"), "Cannot find 'error' option in response");
    });
%}
