### Translate to Pig Latin (XML to XML)

< {%
    request.variables.set("text", "Hello, World!")
%}

POST {{host}}/pig-latin
Content-Type: application/xml
Accept: application/xml

<TranslationRequest>
    <sentence>{{text}}</sentence>
</TranslationRequest>

> {%
    import './scripts/validate-200-response';

    client.test("Response content-type is xml", function () {
        const type = response.contentType.mimeType;
        client.assert(type === "application/xml", `Expected 'application/xml' but received '${type}'`);
    });
%}
