### Translate to Pig Latin

POST {{host}}/pig-latin
Content-Type: application/json
Accept: application/json

{
    "sentence": "Hello, World!"
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is json", function () {
        const type = response.contentType.mimeType;
        client.assert(type === "application/json", `Expected 'application/json' but received '${type}'`);
    });

    client.test("Sentence option exists", function () {
        client.assert(response.body.hasOwnProperty("sentence"), "Cannot find 'sentence' option in response");
    });
%}
