### Translate to Pig Latin (Simple Text)

POST {{host}}/pig-latin
Content-Type: application/json
Accept: application/json

"Hello, World!"

> {%
    import './scripts/validate-200-response';
    import './scripts/validate-content-json';
%}
