### Smoke Test - Translator

POST {{host}}/pig-latin
Content-Type: application/json

{
    "sentence": "Hello, World!"
}

> scripts/validate-200-response.js

### Smoke Test - Swagger UI

GET {{host}}/swagger-ui/index.html

> scripts/validate-200-response.js
