@sut = actuator/count

### Reset Translation Counter
DELETE {{host}}/{{sut}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 204, `Expected '204' but received '${response.status}'`);
    });
%}

### Zero Translation Counter
GET {{host}}/{{sut}}


### Translate first sentence
POST {{host}}/pig-latin
Content-Type: application/json

{
    "sentence": "Hello, World!"
}


### Check Translation Counter
GET {{host}}/{{sut}}


### Translate second sentence
POST {{host}}/pig-latin
Content-Type: application/json

{
    "sentence": "The quick brown fox jumps over the lazy dog."
}

### Second Counter Check
GET {{host}}/{{sut}}


### Set Translation Counter
POST {{host}}/{{sut}}
Content-Type: application/json

{
    "count": 9
}

### Check Changed Counter
GET {{host}}/{{sut}}
