openapi: 3.0.3
info:
  title: Pig Latin translator
  description:
    Pig Latin is a made-up children's language that's intended to be confusing.
    It obeys a few simple rules, but when it's spoken quickly it's really difficult for non-children (and non-native speakers) to understand.
  version: 1.0.0
  license:
    name: MIT License
    url: 'https://spdx.org/licenses/MIT.html'
  contact:
    name: Jegors Čemisovs
    email: jegors.cemisovs@gmail.com
    url: 'https://jc.id.lv'
servers:
  - url: 'http://localhost:8080'
    description: Local server
externalDocs:
    description: Pig Latin exercise on Exercism
    url: 'https://exercism.org/tracks/java/exercises/pig-latin'
tags:
  - name: Translation
    description: |
      Translate text to Pig Latin following the rules:

      1. If a word begins with a vowel sound, add an *"ay"* sound to the end of the word. Please note that "xr" and "yt" at the beginning of a word make vowel sounds (e.g. "xray" -> "xrayay", "yttria" -> "yttriaay").
      2. If a word begins with a consonant sound, move it to the end of the word and then add an "ay" sound to the end of the word. Consonant sounds can be made up of multiple consonants, such as the "ch" in "chair" or "st" in "stand" (e.g. "chair" -> "airchay").
      3. If a word starts with a consonant sound followed by "qu", move it to the end of the word, and then add an "ay" sound to the end of the word (e.g. "square" -> "aresquay").
      4. If a word contains a "y" after a consonant cluster or as the second letter in a two letter word it makes a vowel sound (e.g. "rhythm" -> "ythmrhay", "my" -> "ymay").

paths:
  /pig-latin:
    post:
      summary: Translate text to Pig Latin
      description: Translate text to Pig Latin.
      operationId: translate
      tags:
        - Translation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TranslationRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TranslationResponse'

components:
  schemas:
    TranslationRequest:
      type: object
      required: [text]
      properties:
        text:
          type: string
          description: Text to translate
          example: "Hello world"
    TranslationResponse:
      type: object
      required: [text]
      properties:
        text:
          type: string
          description: Translated text
          example: "Ellohay orldway"
