@sut = actuator/counter

### Read Translation Counter
# @name translationCounter
GET {{host}}/{{sut}}

{{
    translationCounter.count += 5
}}

### Set Translation Counter
# @ref translationCounter

POST {{host}}/{{sut}}
Content-Type: application/json

{{translationCounter}}
