@sut = actuator/count

### Read Translation Counter
GET {{host}}/{{sut}}

> {%
    const counter = parseInt(response.body.count + 5).toString();
    client.global.set('counter', counter);
%}

### Set Translation Counter
POST {{host}}/{{sut}}
Content-Type: application/json

{
    "count": {{counter}}
}
