openapi: 3.1.0
info:
  title: Pig Latin translator
  summary: Translate text to Pig Latin
  description: |
    Pig Latin is a made-up children's language that's intended to be confusing.
    It obeys a few simple rules (below), but when it's spoken quickly it's really difficult for non-children (and non-native speakers) to understand.

    1. If a word begins with a vowel sound, add an `ay` sound to the end of the word. Please note that `xr` and `yt` at the beginning of a word make vowel sounds (e.g. "xray" -> "xrayay", "yttria" -> "yttriaay").
    2. If a word begins with a consonant sound, move it to the end of the word and then add an "ay" sound to the end of the word. Consonant sounds can be made up of multiple consonants, such as the `ch` in "chair" or `st` in "stand" (e.g. "chair" -> "airchay").
    3. If a word starts with a consonant sound followed by `qu`, move it to the end of the word, and then add an `ay` sound to the end of the word (e.g. "square" -> "aresquay").
    4. If a word contains a `y` after a consonant cluster or as the second letter in a two letter word it makes a vowel sound (e.g. "rhythm" -> "ythmrhay", "my" -> "ymay").

  version: 1.0.0
  license:
    name: MIT License
    identifier: MIT
  contact:
    name: Jegors Čemisovs
    email: jegors.cemisovs@gmail.com
    url: 'https://jc.id.lv'
servers:
  - url: 'http://localhost:8080'
    description: Local server
  - url: 'https://piglatin.azurewebsites.net'
    description: Azure server
externalDocs:
  description: Pig Latin exercise on Exercism
  url: 'https://exercism.org/tracks/java/exercises/pig-latin'
tags:
  - name: Translation
    description: |
      Translate english sentence to Pig Latin.
    externalDocs:
      description: Pig Latin
      url: https://en.wikipedia.org/wiki/Pig_Latin

paths:
  /pig-latin:
    post:
      summary: Translate text to Pig Latin
      description: |
        Translate English text to Pig Latin following the rules described in the [description](#/info/description).
      operationId: translate
      tags:
        - Translation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TranslationRequest'
            examples:
              example-1:
                value: { "sentence": "Hello world" }
              example-2:
                value: { "sentence": "Hello, world!" }
              example-3:
                value: { "sentence": "Hello, world! How are you?" }
          application/xml:
            schema:
              $ref: '#/components/schemas/TranslationRequest'
            examples:
              example-1:
                value: |
                  <TranslationRequest>
                    <sentence>The quick brown fox jumps over the lazy dog</sentence>
                  </TranslationRequest>
              example-2:
                value: |
                  <TranslationRequest>
                    <sentence>Hello, world!</sentence>
                  </TranslationRequest>
              example-3:
                value: |
                  <TranslationRequest>
                    <sentence>Hello, world! How are you?</sentence>
                  </TranslationRequest>

      responses:
        '200':
          description: English sentence successfully translated into Pig Latin.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TranslationResponse'
              examples:
                example-1:
                  value: { "sentence": "Ellohay orldway" }
                example-2:
                  value: { "sentence": "Ellohay, orldway!" }
                example-3:
                  value: { "sentence": "Ellohay, orldway! Owhay areay ouyay?" }
            application/xml:
              schema:
                $ref: '#/components/schemas/TranslationResponse'
              examples:
                example-1:
                  value: |
                    <TranslationResponse>
                      <sentence>ethay ickquay ownbray oxfay umpsjay overay ethay azylay ogday</sentence>
                    </TranslationResponse>
                example-2:
                  value: |
                    <TranslationResponse>
                      <sentence>Ellohay, orldway!</sentence>
                    </TranslationResponse>
                example-3:
                  value: |
                    <TranslationResponse>
                      <sentence>Ellohay, orldway! Owhay areay ouyay?</sentence>
                    </TranslationResponse>

        '400':
          description: |
            The request body is invalid. The response body contains the error message.
          content:
            application/json:
              schema:
                $ref: 'schemas/BadRequest.yaml'
              examples:
                example-1:
                  value: { "timestamp": "2021-08-15T12:34:56.789Z", "status": 400, "error": "Bad Request", "path": "/pig-latin" }

        '418':
          description: This cannot be translated into Pig Latin...
          content: {}

components:
  schemas:
    TranslationRequest:
      $ref: 'schemas/TranslationRequest.yaml'
    TranslationResponse:
      $ref: 'schemas/TranslationResponse.yaml'
