GET {{host}}/actuator/health

?? status == 200
?? body status == UP
?? body components.diskSpace.status == UP
?? body components.diskSpace.details.total > 1
?? body components.diskSpace.details.free > 1
