### Translate to Pig Latin

POST {{host}}/pig-latin
Accept-Language: EN
Content-Type: application/json
Accept: application/json

{
    "sentence": "Hello, World!"
}

> {%
    import './scripts/validate-200-response';
    import './scripts/validate-content-json';

    client.test("Sentence option exists", function () {
        client.assert(response.body.hasOwnProperty("sentence"), "Cannot find 'sentence' option in response");
    });

    client.test("Sentence translated correctly", function () {
        const expected = 'ellohay, orldway!'
        const sentence = response.body.sentence
        client.assert(sentence === expected, `Expected '${expected}' but received '${sentence}'`);
    });
%}
