name: API Tests - Hurl

on:
  workflow_dispatch:
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  install-hurl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gacts/install-hurl@v1
      - name: Install hurl and run tests
        run: |
          cd hurl
          hurl --test \
          --variable host=https://piglatin.azurewebsites.net \
          translation-counter.hurl
