name: JetBrains HTTP Client API Tests

on:
  workflow_dispatch:
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  run_ijhttp_api_test:
    name: API Tests by JetBrains HTTP Client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Execute HTTP requests
        uses: madhead/intellij-http-client-action@latest
        with:
          files: |-
            http-client/smoke-test.http
            http-client/body-json-to-json.http
            http-client/body-text-to-json.http
            http-client/body-xml-to-xml.http
            http-client/bad-request.http
            http-client/api-docs.http

          env_file: http-client/http-client.env.json
          env: azure
          report: true
          insecure: true

      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()                # run this step even if previous step failed
        with:
          name: JetBrains HTTP Client API Tests   # Name of the check run which will be created
          path: reports/report.xml                # Path to test results
          reporter: java-junit                    # Format of test results
