name: API Tests - Karate

on:
  workflow_dispatch:

jobs:
  run_karate_api_test:
    name: API Tests by Karate Framework
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Karate API tests
        uses: erikbos/karate-action@main
        with:
          url: https://piglatin.azurewebsites.net
          tests: |
            src/test/java/piglatin/pig-latin-translator.feature
      - name: Publish Test Report
        uses: actions/upload-artifact@v2
        if: always() # This ensures the report is published even if tests fail
        with:
          name: karate-test-reports
          path: target/karate-reports
