# This workflow runs the API tests on the latest version of Ubuntu

name: API Tests - httpYac

on:
  workflow_dispatch:
permissions:
  contents: read
  actions: read
  checks: write
  issues: read
  pull-requests: write
jobs:
  run_httpyac_api_tests:
    name: API Tests by httpYac
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies and run tests
        run: |
          cd http-yac
          npm install
          npm run json

      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: httpYac API Tests
          path: http-yac/report.json
          reporter: mocha-json

      - name: Publish API Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: API Tests by httpYac
          files: http-yac/report.json
