name: bruno cli CI

on:
  workflow_dispatch:

jobs:
  run_bruno_api_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies and run tests
        run: |
          cd bruno-test
          npm install
          npm run test
