# This workflow runs the API tests for the bruno application on the latest version of Ubuntu

name: Bruno API Tests

on:
  workflow_dispatch:
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  run_bruno_api_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies and run tests
        run: |
          cd bruno-test
          npm install
          npm run test
      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure() # always run even if the previous step fails
        with:
          name: Bruno Tests           # Name of the check run which will be created
          path: results.json          # Path to test results
          reporter: mocha-json        # Format of test results
