# This workflow runs the API tests for the bruno application on the latest version of Ubuntu

name: Bruno API Tests

on:
  workflow_dispatch:

jobs:
  run_bruno_api_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies and run tests
        run: |
          cd bruno-test
          npm install
          npm run test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'results.xml'
