name: Unit Tests

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Get java version from pom.xml
        id: java-version
        uses: mavrosxristoforos/get-xml-info@1.1.1
        with:
          xml-file: pom.xml
          xpath: ${{ env.XPATH }}
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ steps.java-version.outputs.info }}
          distribution: 'zulu' # Alternative distribution options are available.
      - name: Build
        run: mvn --batch-mode -DskipTests package
      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
      - name: Test Reporter
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
